#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// 音频配置
#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

// 如果使用 Duplex I2S 模式，请注释下面一行
#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

// I2S麦克风引脚 (INMP441)
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_6

// I2S功放引脚 (MAX98367A)
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16

#else

// I2S麦克风引脚 (INMP441)
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_NC
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6

// I2S功放引脚 (MAX98367A)
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7
#define AUDIO_CODEC_PA_PIN  GPIO_NUM_NC  // MAX98367A不需要PA引脚

#endif

// RGB灯带配置 (WS2812)
#define BUILTIN_LED_GPIO        GPIO_NUM_48
#define BUILTIN_LED_COUNT       1

// 按键配置
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

// 显示屏配置 (ST7789)
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_42
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

// SPI显示屏引脚配置
#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_47
#define DISPLAY_SPI_SCLK_PIN GPIO_NUM_21
#define DISPLAY_SPI_CS_PIN   GPIO_NUM_41
#define DISPLAY_DC_PIN       GPIO_NUM_40
#define DISPLAY_RST_PIN      GPIO_NUM_45

#endif // _BOARD_CONFIG_H_